# Setup
title:               Nicolas Seinturier
tagline:             'Blog'
description:         'Sections'
url:                 //nseinturier.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              nseinturier
  url:               
  email:             nicolas.seinturier@dauphine.eu

# Gems
plugins:
  - jekyll-paginate
# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Build settings
kramdown:
  math_engine: katex